name: Build Linux

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update dependencies
        run: sudo apt-get update

      - name: Install specific dependencies
        run: sudo apt install gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1

      - name: Build Linux
        run: |
          echo "Building Linux amd64..."
          export TAG_NAME="${{ github.event.release.tag_name }}"
          export ARCH="amd64"
          CGO_ENABLED=1 GOOS=linux GOARCH=$ARCH go build -o ./dist/$ARCH/Gio-Translator .
          cp ./LICENSE ./dist/$ARCH
          tar -cJf ./dist/Gio-Translator-linux-$TAG_NAME-$ARCH.tar.xz --directory=./dist/$ARCH Gio-Translator ./LICENSE
          rm -rf ./dist/$ARCH

      - name: Upload Release Asset
        run: |
          export TAG_NAME="${{ github.event.release.tag_name }}"
          export REF_NAME="${{ github.ref_name }}"
          gh release upload $TAG_NAME ./dist/Gio-Translator-linux-$REF_NAME-amd64.tar.xz
