name: Build Windows

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1

      - name: Install gogio tool
        run: go install gioui.org/cmd/gogio@latest

      - name: Build Windows
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          echo "Building Windows..."
          gogio -target=windows -arch=amd64 -o dist\amd64\Gio-Translator.exe .
          gogio -target=windows -arch=386 -o dist\i386\Gio-Translator.exe .
          powershell -Command "Compress-Archive -Path dist\amd64\Gio-Translator.exe -Destination dist\Gio-Translator-windows-$env:TAG_NAME-amd64.zip"
          powershell -Command "Compress-Archive -Path dist\i386\Gio-Translator.exe -Destination dist\Gio-Translator-windows-$env:TAG_NAME-i386.zip"
          Remove-Item -Path .\dist\amd64 -Recurse
          Remove-Item -Path .\dist\i386 -Recurse

      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          gh release upload $TAG_NAME ./dist/Gio-Translator-windows-$REF_NAME-amd64.zip
          gh release upload $TAG_NAME ./dist/Gio-Translator-windows-$REF_NAME-i386.zip
        
